# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60bced7b5e6ec768f87f422e20747b1a3d86147f539c964133b98ace541f10e9579370bbdd6a2493b1de509ee542779c6cf356c7158a407b9e138adb1fb3e002

test:
  secret_key_base: cfc67c14946f9e855763658a183b7eb6db70f41e7c1a263007e0a275aea5a5d965931af56a3b4da999e82e3ad4c4016806a8f23cf8e6e14c1baf0a5f698deb0a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
